name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout ️
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} ♨️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Specify the Bun version you want to use

      - name: Create .env file (Secure Secret)
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
        env:
          # Mask the secret values in logs
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}"
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}"

      - name: Install & Generate
        run: |
          bun install
          bun run generate
        env:
          NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
